import { AuthProvider, UserInfo } from '@models/index'

export const mockUserList: UserInfo[] = [
  {
    uid: 'D53dGIMqazHhm45Enfa8rTcxkTvp',
    photoURL: '',
    authProvider: AuthProvider.GOOGLE,
    phoneNumber: '',
    gender: '',
    name: 'Panda Mountain',
    dateOfBirth: '',
    tgLink: '',
    email: 'panda.mountain.657@example.com',
    bio: 'asdasd',
  },
  {
    uid: 'G6g9rSE7Q41C4CWTzGG5fErInBQS',
    authProvider: AuthProvider.GOOGLE,
    photoURL:
      'http://127.0.0.1:9097/v0/b/modsen-twitter-95f28.appspot.com/o/G6g9rSE7Q41C4CWTzGG5fErInBQS?alt=media&token=5a6d5d57-5ea0-4ef4-9ee0-f254ade887fb',
    phoneNumber: '',
    gender: 'RACOON',
    name: 'Raccoon Otter',
    bio: 'bio',
    dateOfBirth: '',
    tgLink: 'https://t.me/test_tg',
    email: 'raccoon.otter.366@example.com',
  },
  {
    uid: 'eVUHGkNiYSLcWtCYfNAFP28P2lTw',
    photoURL: '',
    authProvider: AuthProvider.GOOGLE,
    phoneNumber: '',
    gender: '',
    name: 'Mountain Raccoon',
    bio: '',
    dateOfBirth: '',
    tgLink: '',
    email: 'mountain.raccoon.991@example.com',
  },
  {
    uid: 'qkqxB9FNjDvKHFguag97K4t22jsk',
    photoURL: '',
    authProvider: AuthProvider.GOOGLE,
    phoneNumber: '',
    gender: '',
    name: 'Chicken Mountain',
    bio: '',
    dateOfBirth: '',
    tgLink: '',
    email: 'chicken.mountain.993@example.com',
  },
  {
    uid: 'qasdkqxB9FNjDvKHFguag97K4t22jsk',
    photoURL: '',
    authProvider: AuthProvider.EMAIL,
    phoneNumber: '+375292200011',
    gender: '',
    name: 'Donkey River',
    bio: '',
    dateOfBirth: '2000-03-22',
    tgLink: '',
    email: 'donkey.river.228@example.com',
  },
]
