name: E2E tests
on: [push]
jobs:
  E2ETests:
    name: E2E tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: yarn install
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: yarn emulate & yarn dev

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
