name: Test
on: [push]
jobs:
  unitTest:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
