name: Unit tests
on: [push]
jobs:
  unitTest:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: yarn install

      - run: yarn test:unit
